<a href="https://colab.research.google.com/github/DavideScassola/PML2024/blob/main/Notebooks/02_numpy_pandas_sklearn/021_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 1.2: Introduzione a `numpy`

Machine Learning Probabilistico -- Primavera 2026, UniTS


## Cos'è `numpy`?


<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1280px-NumPy_logo_2020.svg.png" width="400">


NumPy (Numerical Python) è il pacchetto fondamentale per il calcolo scientifico in Python; mi fornisce supporto per array multidimensionali e molte funzioni matematiche che operano su di essi. Queste includono:

- operazioni matematiche
- algebra lineare
- operazioni statistiche di base
- simulazioni casuali (random)

e molto altro.

Inoltre, le operazioni sugli array con NumPy sono davvero veloci, poiché si basano su codice compilato in C.

Python

In [ ]:
import numpy as np
# Questo è il modo standard con cui lo importo

## Array
Al centro del pacchetto NumPy si trova l'oggetto `ndarray` (array n-dimensionale). Questo incapsula array n-dimensionali composti da tipi di dati omogenei. Noto diverse differenze importanti tra gli array NumPy e le classiche sequenze standard di Python:

- Hanno una dimensione fissa stabilita alla creazione
- Tutti gli elementi devono essere dello stesso tipo (es. float)
- Supportano operazioni matematiche (es. posso sommare due array)

Un modo in cui posso inizializzare gli array NumPy è partendo dalle liste Python, usando liste nidificate per creare dati a due o più dimensioni:

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Un array NumPy è caratterizzato da un tipo di dato (`.dtype`) e da una forma (`.shape`):

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

print('a:\n', a)
print('type:', a.dtype)
print('shape:', a.shape) 

a:
 [1 2 3 4 5 6]
type: int64
shape: (6,)


In [5]:
a = np.array([[1, -2, 3.6, 4], [5, 6.0, 7, 8], [9, 10, 1.0, 2.2]])

print('a:\n', a)
print('type:', a.dtype)
print('shape:', a.shape) 

a:
 [[ 1.  -2.   3.6  4. ]
 [ 5.   6.   7.   8. ]
 [ 9.  10.   1.   2.2]]
type: float64
shape: (3, 4)


In NumPy, chiamo le dimensioni **assi**. Ad esempio, l'array precedente con forma (shape) (3, 4) ha due **assi**: il primo **asse** ha lunghezza 3 e il secondo **asse** ha lunghezza 4.

## Indicizzazione e Slicing

Posso indicizzare e fare lo slicing degli array NumPy negli stessi identici modi in cui lo faccio con le liste Python:

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])

a[0] # Accesso al primo elemento

np.int64(1)

In [7]:
a[-2] # Accesso al penultimo elemento

np.int64(5)

In [8]:
# Modifico un elemento dell'array
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

Lo slicing mi serve per selezionare un sottoinsieme di elementi di un array; la notazione per selezionare gli elementi di un array da `start` (incluso) a `stop` (escluso) è:

`array[start : stop]`

oppure 

`array[start : stop : step]`

se voglio impostare un passo (step) diverso da 1.

In [ ]:
a[0:2]

In [ ]:
a[1:-2]

In [ ]:
a[2:] # Vado implicitamente fino alla fine dell'array

In [ ]:
a[:4] # Parto implicitamente dall'inizio dell'array

In [ ]:
a[::2] # Modifico la dimensione del passo (step)

In [ ]:
a[::-1] # Inverto l'array

<img src="https://numpy.org/doc/stable/_images/np_indexing.png" width="1000">

Con gli array multidimensionali, posso specificare un indice/slice per ogni singolo **asse**:

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a[1:3, -2:]

array([[ 7,  8],
       [11, 12]])

In [11]:
# Non ho bisogno di specificare lo slice/indice per tutti gli assi, gli assi che non specifico verranno considerati come slice completi [:]
a[1:3] # equivale a a[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<img src="https://numpy.org/doc/stable/_images/np_matrix_indexing.png" width="1000">

## Operazioni sugli array

Una delle caratteristiche e dei vantaggi principali di NumPy sono le operazioni **vettorializzate**:

In [ ]:
a = np.array([20, 30, 40, 50])
b = np.array([1, 2, 3, 4])

c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
2*a + 1

In [ ]:
a + b # Somma elemento per elemento

In [ ]:
a**2

In [ ]:
np.log(a)

In [ ]:
c + c**2

## Statistiche

In [13]:
a = np.array([20, 30, 40, 50, 12, 90, 23])

In [14]:
np.sum(a)

np.int64(265)

In [15]:
np.mean(a)

np.float64(37.857142857142854)

In [16]:
np.std(a)

np.float64(24.321821897385963)

In [17]:
np.max(a)

np.int64(90)

In [18]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
np.sum(b)

np.int64(78)

In [20]:
# Riduco l'array lungo l'asse specificato
# (3, 4) -> (4)
np.sum(b, axis=0)

array([15, 18, 21, 24])

In [ ]:
# (3, 4) -> (3)
np.sum(b, axis=1)

<img src="https://numpy.org/doc/stable/_images/np_matrix_aggregation.png" width="1000">

<img src="https://numpy.org/doc/stable/_images/np_matrix_aggregation_row.png" width="1000">

## Rifiutare i cicli, abbracciare la **vettorializzazione**!

Le operazioni vettorializzate sono ordini di grandezza più veloci rispetto ai cicli (loop) in python.
A meno che non mi sia strettamente necessario, dovrei **evitare del tutto di usare i cicli**!

Ne faccio subito una dimostrazione; supponiamo di voler trovare il valore massimo in un array molto grande:

In [21]:
a = np.arange(30_000_000) # creo un array con elementi che vanno da 0 a n-1
a

array([       0,        1,        2, ..., 29999997, 29999998, 29999999],
      shape=(30000000,))

Questo è il modo inefficiente per farlo:

In [22]:
# modo inefficiente
max_value = a[0] 
for i in a:
    if i>max_value:
        max_value = i
max_value

np.int64(29999999)

L'operazione vettorializzata al contrario è nettamente più veloce:

In [ ]:
np.max(a)

In [ ]:
del a

## Rimodellamento (Reshaping)

A volte mi può tornare utile cambiare la forma (reshape) degli array:

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("a.shape:", a.shape)
a

In [ ]:
a = a.reshape(3, 4)
print("a.shape:", a.shape)
a

In [ ]:
a = a.reshape(3, 2, 2)
print("a.shape:", a.shape)
a

Noto che in questo modo l'ordine lessicografico viene preservato.

In [23]:
a.reshape(-1, 2) # -1 significa che deduco il valore dalla lunghezza dell'array e dalle dimensioni rimanenti

array([[       0,        1],
       [       2,        3],
       [       4,        5],
       ...,
       [29999994, 29999995],
       [29999996, 29999997],
       [29999998, 29999999]], shape=(15000000, 2))

In [ ]:
a.reshape(-1, 1) # Mi è utile?

**Convenzione molto importante**:

Quando lavoro su un dataset, la prima dimensione/asse rappresenta sempre il numero di osservazioni. Molte funzioni scientifiche e librerie lo danno per scontato!

Ad esempio, se ho un dataset di $n$ osservazioni e ogni osservazione ha $p$ feature, allora il mio array dovrà avere una forma (shape) `(n, p)`.

## Random

Il modulo `random` di NumPy contiene diverse funzioni per campionare da molte distribuzioni statistiche:

In [24]:
np.random.normal(loc=0, scale=1, size=(3, 2))

array([[-1.47384827, -1.6025625 ],
       [ 0.42383609, -0.07408231],
       [ 0.41023604,  0.40723154]])

In [25]:
np.random.binomial(n=10, p=0.2, size=7)  # n è il numero di tentativi, p è la probabilità di successo

array([0, 3, 2, 1, 3, 2, 2])

## Broadcasting

Ho visto come eseguire operazioni binarie elemento per elemento tra due (o più) array (es. la somma). Noto che l'ho fatto solo tra array che avevano la stessa forma (shape).

Ora considero il seguente array di forma `(4,2)`:

In [ ]:
a = np.arange(8).reshape(4, 2)
a

Ora suppongo di voler aggiungere a ogni singola riga il seguente array:

In [ ]:
b = np.array([-1, -10])
b

In [ ]:
b.shape

Potrei fare un ciclo for in cui seleziono iterativamente le righe della matrice e aggiungo quell'array, ma ricordo bene, non è così che si fa qui!
NumPy mi offre un'eccellente alternativa a questo:

In [ ]:
a + b.reshape(1,2)

Cosa è successo?

L'array `a` ha forma `(4,2)` mentre l'array `b` ha forma `(1,2)`.
Numpy ha **espanso** l'array `b` a `(4,2)` ripetendolo 4 volte, dopodiché ha calcolato la somma.

Il Broadcasting è un meccanismo che permette a NumPy di eseguire operazioni su array di forme diverse. Le dimensioni del mio array devono essere compatibili, ad esempio, quando le dimensioni di entrambi gli array sono uguali o quando una di esse è esattamente 1. Se le dimensioni non sono compatibili, Python mi restituirà un `ValueError`.

<img src="https://www.w3resource.com/w3r_images/python-numpy-exercise-124.svg" width="700">

In [ ]:
# Un altro esempio
row_vector = np.array([10, 20, 30]).reshape(1, 3)  # shape: (1,3)
col_vector = np.array([1, 2, 3]).reshape(3, 1)  # shape: (3,1)

print('row_vector:\n', row_vector)
print('col_vector:\n', col_vector)

print('row_vector + col_vector:\n', row_vector + col_vector) # (1,3) + (3,1) -> (3,3)

## Viste (Views) e Copie (Copies)

Quando eseguo operazioni sugli array, a volte gli array originali vengono copiati e a volte no, a seconda dell'operazione specifica.

In [ ]:
a = np.zeros(5) # equivale a np.array([0, 0, 0, 0, 0])
a

In [ ]:
b = a[:-1]
b[0] = 77
print('a: ', a)
print('b: ', b)

Il solo uso dell'operatore di assegnazione `=` o dello slicing non mi crea una copia a sé stante (si tratta solo di una 'view', per cui modificando 'b' si è modificato anche l'originale 'a')!

Lo stesso identico comportamento accade quando eseguo lo slicing unito al reshaping.

Altre operazioni, invece, mi creano automaticamente una copia vera e propria:

In [ ]:
a = np.zeros(5)
b = a + 1
b[0] = 77
print('a: ', a)
print('b: ', b)

Se voglio esplicitamente creare una copia profonda (deepcopy) slegata di un array, posso usare il metodo dedicato `.copy()`.